/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.onlinestore.orders;

import io.vertx.core.Vertx;
import io.vertx.core.VertxOptions;

public class OrderServiceApplication {

	public static void main(String[] args) {

		// Vertx vrts = Vertx.vertx();

		Vertx.clusteredVertx(new VertxOptions(), handler -> {
			if (handler.succeeded()) {
				handler.result().deployVerticle(new OrderService(3002));

			}
		});
		// vrts.deployVerticle(new OrderService(3002));
		while (true);
	}

}
