/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.onlinestore.products;

import io.vertx.core.Vertx;
import io.vertx.core.VertxOptions;

public class ProductServiceApplication {

	public static void main(String[] args) {

		Vertx.clusteredVertx(new VertxOptions(), handler -> {
			if (handler.succeeded()) {
				handler.result().deployVerticle(new ProductService(3001));

			}
		});
		// vrts.deployVerticle(new OrderService(3002));
		while (true);
	}

}
